version: 2.0

jobs:
  build:
    docker:
      - image: asciidoctor/docker-asciidoctor
    working_directory: ~/circleci
    steps:
      - checkout
      - run: apk -Uuv add groff less python py-pip
      - run: pip install awscli
      - run: asciidoctor index.adoc
      - run: aws s3 sync ~/circleci s3://open-rpg/ --delete --cache-control "max-age=3600" --acl "public-read"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
