version: 2.0

jobs:
  build:
    docker:
      - image: asciidoctor/docker-asciidoctor
    working_directory: ~/circleci
    steps:
      - checkout
      - run: pip install awscli
      - run: asciidoctor index.adoc
      - run: aws s3 sync ~/circleci s3://open-rpg/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
