= Attributes

The character's attributes provide a quick way to describe it's physical and mental capabilities. They serve as a helpful tool to understand and simulate these properties.

== Primary attributes

There are six *primary attributes* in the game. These primary attributes show the very basic capabilities of the character. For example, if your character is strong or weak, intelligent or foolish. These primary attributes can't go under 1 in any case. If that would happen the character dies immediately instead.

== Attribute modifiers

Each attribute has a modifier value that affects certain properties of the character. These properties for each attribute are discussed bellow. To calculate the bonus value for an attribute you need to use the following chart:

TODO: Ability bonus chart!

== Secondary attributes

There are two *secondary attributes* for each primary one. They represent the different aspects of the primary attributes they belong to. For each modifier you have on your primary attribute you can allocate one point on your secondary attribute.

[TIP]
====
For example, if your character has 17 strength, it will get 4 attribute modifiers for stamina or muscle. You can play him as a very muscular warrior (4 muscle and 0 endurance) or a legionary who is not quite muscular but could march for an extended time, often days (0 muscle and 4 endurance) or someone who doesn't have the biggest muscles nor could march for days but somewhere in-between (muscle 3 and 1 endurance).
====

== Strength

The *Stamina* attribute describes the character's muscle efficiency. For example, how long can it lift weights or do exhausting activities without getting tired.

.Properties affected by Strength
* Meele damage
* Meele attack

=== Stamina

The *Stamina* attribute describes the character's muscle efficiency. For example, how long can it lift weights or do exhausting activities without getting tired.

.Properties affected by Stamina
* Carrying capacity
* Fatigue & Exhaustion
* Springing
* Proficiencies

=== Muscle

The *Muscle* attribute measures the character's sheer power. A character with high Muscle looks very muscular and able to lift or bend items easily.

.Properties affected by Muscle
* Force opening objects
* Lifting/bending objects

== Dexterity

The *Dexterity* attribute describes the character's hand-eye coordination, reaction time and balance.

.Properties affected by Dexterity
* Ranged damage
* Ranged attack

=== Reflex

The *Reflex* attribute describes how quickly could the character react to a change in his or her environment or do actions quickly. A character with high reflexes might be a sleight-of-hand expert or a quick-shooter artist. He or she could feel the time slowing down when doing quick actions or react to traps or immediate changes in his environment.

.Properties affected by Reflex
* Initiation
* Improve running speed
* Improve attack speed for certain classes

=== Balance

The *Balance* attribute describes the character's ability to do acrobatic movements, climb walls or other objects, do activities that require precise hand motions.

.Properties affected by Balance
* Acrobatics related skills
* Opening locks
* Picking pockets
* Moving silently
* Climbing walls or other objects

== Constitution

=== Health

.Properties affected by Health
* How hard is to weaken or kill the character with poisons
* Increase hitpoints when the character rolls at level ups

=== Resistance

.Properties affected by Resistance
* How much physical abouse could the character survive when interrogated
* Chance of surviving near-death experiences

== Intelligence

...

=== Reason

...

=== Knowledge

...

== Wisdom

...

=== Intuition

...

=== Willpower

...

== Charisma

Charisma is the force of the character's personality. How good is it with manipulating and inspiring people.

=== Leadership

...

=== Comeliness

Comeliness describes the attractiveness of the character. It could influence situations when intricate social interactions are necessary. Different races get bonuses to Comeliness for each other race. For example, an orc would get zero bonuses to Comeliness when meeting another orc but -4 when meeting a human.