name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: asciidoctor/docker-asciidoctor

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python
        run: apk -Uuv add groff less python py-pip

      - name: Install AWS CLI
        run: pip install awscli

      - name: Build the website
        run: asciidoctor index.adoc

      - name: Upload the website
        run: aws s3 sync ~/circleci s3://open-rpg/ --delete --cache-control "max-age=3600" --acl "public-read"
