name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Install AWS CLI
        run: sudo pip install awscli

      - name: Build the website
        run: sudo asciidoctor index.adoc

      - name: Upload the website
        run: sudo aws s3 sync ~/circleci s3://open-rpg/ --delete --cache-control "max-age=3600" --acl "public-read"
